[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = "dist"

  # SPA setup
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  [dev]
    command = "yarn dev"
    port = 3000
    publish = "dist"
