- name: Deploy code changes
  hosts: servers

  tasks:
    - name: Update Caddy configuration
      copy:
        src: Caddyfile
        dest: /etc/caddy/Caddyfile

    - name: Reload Caddy
      service:
        name: caddy
        state: reloaded

    - name: Update frontend assets
      copy:
        src: ../frontend/dist
        dest: /srv/frontend

    - name: Update backend
      copy:
        src: ../backend/davinci_backend
        dest: /srv
