- name: Deploy code changes
  hosts: servers

  tasks:
    - name: Update Caddy configuration
      copy:
        src:
        dest:

    - name: Update frontend assets
      copy:
        src: ../frontend/dist
        dest: /srv/assets

    - name: Update backend
      copy:
        src: ../backend
        dest: /srv
